metrics_bind_addr = "0.0.0.0:3001"
writer = "log" # "log" prints to stdout, "influx" writes to InfluxDB

[weather_api_config]
weather_api_key = "${WEATHER_API_KEY}"
scheme = "http"
host = "api.weatherapi.com"
coords = "${COORDS}"
poll_interval_secs = 10 # development, in live it should be >=60 sec

[influx_db_config]
host = "192.168.2.27"
port = 8086
database = "weatherapi_com"
token = "${INFLUXDB_TOKEN}"